{% set name = "reef3d" %}
{% set version = "25.11" %}
{% set sha256 = "a48c75f1d2ac079f5adca490512a1441062e95531a54fff10b968997ca1c2234" %}

{% set mpi = mpi or 'openmpi' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/REEF3D/REEF3D/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script_env:
    - VERSION={{ version }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - {{ mpi }}
  host:
    - {{ mpi }}
    - eigen =3.3.8
    - hypre
  run:
    - {{ mpi }}
    - hypre
    - divemesh
    - libcxx

test:
  commands:
    - test -f $PREFIX/bin/reef3d

about:
  home: https://reef3d.wordpress.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "REEF3D : Open-Source Hydrodynamics"
  description: |
    REEF3D is an open-source hydrodynamics framework.  The software is efficiently parallelized, 
    designed to run on a large number of processors. High-order spatial and temporal discretization 
    schemes result in accurate and stable numerical behavior. The modular programming approach 
    allows the framework to incorporate a range of different flow solvers which together represent
    all relevant length scales. With a focus on coastal, marine and hydraulic engineering flows, 
    tailor-made multiphysics solvers are available for a range of relevant problems 
    (e.g. sediment transport or floating body dynamics).

extra:
  recipe-maintainers:
    - mattkram
